### ISSUE TITLE
Build error on macOS

### ISSUE THREAD

**Issue by tiann** [aya-rs/aya#324]
```
❯ cargo xtask build-ebpf
    Finished dev [unoptimized + debuginfo] target(s) in 0.44s
     Running `target/debug/xtask build-ebpf`
       Fresh core v0.0.0 (/Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core)
       Fresh unicode-ident v1.0.1
       Fresh rustc-std-workspace-core v1.99.0 (/Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/rustc-std-workspace-core)
       Fresh compiler_builtins v0.1.73
       Fresh proc-macro2 v1.0.39
       Fresh quote v1.0.18
       Fresh aya-bpf-cty v0.2.1 (https://github.com/aya-rs/aya?branch=main#24597b15)
       Fresh aya-log-common v0.1.11-dev.0 (https://github.com/aya-rs/aya-log?branch=main#1b0d3da1)
       Fresh test-common v0.1.0 (/private/tmp/test/test-common)
       Fresh syn v1.0.96
       Fresh aya-bpf-bindings v0.1.0 (https://github.com/aya-rs/aya?branch=main#24597b15)
       Fresh aya-bpf-macros v0.1.0 (https://github.com/aya-rs/aya?branch=main#24597b15)
       Fresh aya-log-ebpf-macros v0.1.0 (https://github.com/aya-rs/aya-log?branch=main#1b0d3da1)
       Fresh aya-bpf v0.1.0 (https://github.com/aya-rs/aya?branch=main#24597b15)
       Fresh aya-log-ebpf v0.1.0 (https://github.com/aya-rs/aya-log?branch=main#1b0d3da1)
   Compiling test-ebpf v0.1.0 (/private/tmp/test/test-ebpf)
     Running `rustc --crate-name test --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C metadata=2e82d0e5b2d39d7d -C extra-filename=-2e82d0e5b2d39d7d --out-dir /private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps --target bpfel-unknown-none -L dependency=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps -L dependency=/private/tmp/test/test-ebpf/../target/debug/deps --extern aya_bpf=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_bpf-8eafcb4491315b37.rlib --extern aya_log_ebpf=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_log_ebpf-dab76645e270effc.rlib --extern 'noprelude:compiler_builtins=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libcompiler_builtins-fb7baa4459bc0f28.rlib' --extern 'noprelude:core=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libcore-ac93b7c2e8668cc4.rlib' --extern test_common=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libtest_common-46aaf21c6fd808b3.rlib -Z unstable-options`
error: linking with `bpf-linker` failed: exit status: 101
  |
  = note: "bpf-linker" "--export-symbols" "/var/folders/zf/ddjjdvfx7sbdpg9m2v_dzq6c0000gn/T/rustcI90ALy/symbols" "/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/test-2e82d0e5b2d39d7d.test.964645a3-cgu.0.rcgu.o" "-L" "/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps" "-L" "/private/tmp/test/test-ebpf/../target/debug/deps" "-L" "/Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/bpfel-unknown-none/lib" "--cpu" "generic" "--cpu-features" "" "-L" "/Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/bpfel-unknown-none/lib" "-o" "/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/test-2e82d0e5b2d39d7d" "-O3" "--debug"
  = note: Unable to find LLVM shared lib in possible locations:
          - /Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib
          - /private/tmp/test/test-ebpf/../target/debug/deps
          - /Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib
          - /Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib
          - /private/tmp/test/target/debug/deps
          - /private/tmp/test/target/debug
          - /Users/weishu/.rustup/toolchains/stable-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib
          - /Users/weishu/.rustup/toolchains/stable-x86_64-apple-darwin/lib
          - /Users/weishu/lib
          - /usr/local/lib
          - /usr/lib
          - /Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/x86_64-apple-darwin/lib
          - /Users/weishu/.cargo/lib
          - /Users/weishu/.cargo/lib
          - /Users/weishu/.cargo/lib
          - /Users/weishu/.pyenv/lib
          - /Users/weishu/perl5/lib
          - /opt/local/lib
          - /usr/local/lib
          - /usr/lib
          - /lib
          - /usr/lib
          - /Users/weishu/dev/env/android-sdk-macosx/lib
          - /usr/local/opt/binutils/lib
          - /usr/local/lib
          - /usr/lib
          - /lib
          - /usr/lib
          - /lib
          - /Applications/VMware Fusion.app/Contents/lib
          - /usr/local/go/lib
          - /Library/Apple/usr/lib
          - /Users/weishu/.cargo/lib
          - /Users/weishu/dev/env/android-sdk-macosx/lib
          - /usr/local/go/lib
          - /Users/weishu/.fzf/lib
          thread 'main' panicked at 'explicit panic', /Users/weishu/.cargo/registry/src/rsproxy.cn-8f6827c7555bfaf8/aya-rustc-llvm-proxy-0.4.0/src/lib.rs:66:17
          stack backtrace:
             0:        0x103b884d4 - std::backtrace_rs::backtrace::libunwind::trace::h3cae2b905fd8ac13
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
             1:        0x103b884d4 - std::backtrace_rs::backtrace::trace_unsynchronized::he35fb4c47e25f88c
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
             2:        0x103b884d4 - std::sys_common::backtrace::_print_fmt::hdb42afc2298dc41a
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
             3:        0x103b884d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc80096156cd24709
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
             4:        0x103b9e49b - core::fmt::write::hb6b947db0e571766
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
             5:        0x103b85c88 - std::io::Write::write_fmt::h59c4febf5f8fcb1e
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
             6:        0x103b89ccd - std::sys_common::backtrace::_print::h72a3180302df7468
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
             7:        0x103b89ccd - std::sys_common::backtrace::print::ha0747cec3f48ad89
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
             8:        0x103b89ccd - std::panicking::default_hook::{{closure}}::h0e76f92bbb367061
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
             9:        0x103b899b1 - std::panicking::default_hook::hbbbb8c05ad6cce9a
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
            10:        0x103b8a24e - std::panicking::rust_panic_with_hook::ha581a2c99399f83b
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
            11:        0x103b657ab - std::panicking::begin_panic::{{closure}}::hc57fe083ca1eea73
            12:        0x103b65777 - std::sys_common::backtrace::__rust_end_short_backtrace::h9620d44d0f370b03
            13:        0x103ba7b6d - std::panicking::begin_panic::hedb03f8528414ed1
            14:        0x103b6345a - std::sync::once::Once::call_once::{{closure}}::h80d062e613295e1b
            15:        0x103ba9c45 - std::sync::once::Once::call_inner::h8b33a57e6782c624
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sync/once.rs:434:21
            16:        0x103b61c5f - _LLVMInitializeBPFTarget
            17:        0x103afb325 - bpf_linker::llvm::init::hdf4839966017a037
            18:        0x103af558f - bpf_linker::linker::Linker::link::h662e8b3751512a65
            19:        0x103aed566 - bpf_linker::main::h6ca1e7dc87cd9f3a
            20:        0x103af3126 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8879b42cc2650929
            21:        0x103ae117c - std::rt::lang_start::{{closure}}::hcac71c8faace75ca
            22:        0x103b7fb5a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h45b43bdd91db95dd
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
            23:        0x103b7fb5a - std::panicking::try::do_call::h249f439f16aa313c
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
            24:        0x103b7fb5a - std::panicking::try::ha8537a1873fa2ff9
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
            25:        0x103b7fb5a - std::panic::catch_unwind::hffa61ccaeb4f89c5
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
            26:        0x103b7fb5a - std::rt::lang_start_internal::{{closure}}::h32bbf4c39987b002
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
            27:        0x103b7fb5a - std::panicking::try::do_call::h558936e01b59417c
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
            28:        0x103b7fb5a - std::panicking::try::h12a630e8ced1b46a
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
            29:        0x103b7fb5a - std::panic::catch_unwind::h539ca15d1ec773ea
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
            30:        0x103b7fb5a - std::rt::lang_start_internal::hdb19fe6764e59ca8
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
            31:        0x103aedd39 - _main


error: could not compile `test-ebpf` due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name test --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C metadata=2e82d0e5b2d39d7d -C extra-filename=-2e82d0e5b2d39d7d --out-dir /private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps --target bpfel-unknown-none -L dependency=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps -L dependency=/private/tmp/test/test-ebpf/../target/debug/deps --extern aya_bpf=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_bpf-8eafcb4491315b37.rlib --extern aya_log_ebpf=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_log_ebpf-dab76645e270effc.rlib --extern 'noprelude:compiler_builtins=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libcompiler_builtins-fb7baa4459bc0f28.rlib' --extern 'noprelude:core=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libcore-ac93b7c2e8668cc4.rlib' --extern test_common=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libtest_common-46aaf21c6fd808b3.rlib -Z unstable-options` (exit status: 1)
thread 'main' panicked at 'assertion failed: status.success()', xtask/src/build_ebpf.rs:62:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by tiann** [comment]
I found the error:

> Unable to find LLVM shared lib in possible locations

So i tried compile llvm myself and got the correct dylib, but it still compiles failed:

```
❯ cargo xtask build-ebpf
    Finished dev [unoptimized + debuginfo] target(s) in 0.42s
     Running `target/debug/xtask build-ebpf`
       Fresh core v0.0.0 (/Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core)
       Fresh unicode-ident v1.0.1
       Fresh rustc-std-workspace-core v1.99.0 (/Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/rustc-std-workspace-core)
       Fresh proc-macro2 v1.0.39
       Fresh compiler_builtins v0.1.73
       Fresh quote v1.0.18
       Fresh aya-bpf-cty v0.2.1 (https://github.com/aya-rs/aya?branch=main#24597b15)
       Fresh aya-log-common v0.1.11-dev.0 (https://github.com/aya-rs/aya-log?branch=main#1b0d3da1)
       Fresh test-common v0.1.0 (/private/tmp/test/test-common)
       Fresh syn v1.0.96
       Fresh aya-bpf-bindings v0.1.0 (https://github.com/aya-rs/aya?branch=main#24597b15)
       Fresh aya-bpf-macros v0.1.0 (https://github.com/aya-rs/aya?branch=main#24597b15)
       Fresh aya-log-ebpf-macros v0.1.0 (https://github.com/aya-rs/aya-log?branch=main#1b0d3da1)
       Fresh aya-bpf v0.1.0 (https://github.com/aya-rs/aya?branch=main#24597b15)
       Fresh aya-log-ebpf v0.1.0 (https://github.com/aya-rs/aya-log?branch=main#1b0d3da1)
   Compiling test-ebpf v0.1.0 (/private/tmp/test/test-ebpf)
     Running `rustc --crate-name test --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C metadata=2e82d0e5b2d39d7d -C extra-filename=-2e82d0e5b2d39d7d --out-dir /private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps --target bpfel-unknown-none -L dependency=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps -L dependency=/private/tmp/test/test-ebpf/../target/debug/deps --extern aya_bpf=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_bpf-8eafcb4491315b37.rlib --extern aya_log_ebpf=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_log_ebpf-dab76645e270effc.rlib --extern 'noprelude:compiler_builtins=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libcompiler_builtins-fb7baa4459bc0f28.rlib' --extern 'noprelude:core=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libcore-ac93b7c2e8668cc4.rlib' --extern test_common=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libtest_common-46aaf21c6fd808b3.rlib -Z unstable-options`
error: linking with `bpf-linker` failed: exit status: 101
  |
  = note: "bpf-linker" "--export-symbols" "/var/folders/zf/ddjjdvfx7sbdpg9m2v_dzq6c0000gn/T/rustcxrdy8f/symbols" "/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/test-2e82d0e5b2d39d7d.test.964645a3-cgu.0.rcgu.o" "-L" "/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps" "-L" "/private/tmp/test/test-ebpf/../target/debug/deps" "-L" "/Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/bpfel-unknown-none/lib" "--cpu" "generic" "--cpu-features" "" "-L" "/Users/weishu/.rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/bpfel-unknown-none/lib" "-o" "/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/test-2e82d0e5b2d39d7d" "-O3" "--debug"
  = note: Unable to find symbol 'LLVMInitializeBPFTarget' in the LLVM shared lib
          thread 'main' panicked at 'explicit panic', /var/folders/zf/ddjjdvfx7sbdpg9m2v_dzq6c0000gn/T/cargo-installjXAzdV/release/build/aya-rustc-llvm-proxy-4e9be42bde8ad946/out/llvm_gen.rs:1024:1
          stack backtrace:
             0:        0x1057664d4 - std::backtrace_rs::backtrace::libunwind::trace::h3cae2b905fd8ac13
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
             1:        0x1057664d4 - std::backtrace_rs::backtrace::trace_unsynchronized::he35fb4c47e25f88c
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
             2:        0x1057664d4 - std::sys_common::backtrace::_print_fmt::hdb42afc2298dc41a
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:66:5
             3:        0x1057664d4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hc80096156cd24709
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:45:22
             4:        0x10577c49b - core::fmt::write::hb6b947db0e571766
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/fmt/mod.rs:1194:17
             5:        0x105763c88 - std::io::Write::write_fmt::h59c4febf5f8fcb1e
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/io/mod.rs:1655:15
             6:        0x105767ccd - std::sys_common::backtrace::_print::h72a3180302df7468
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:48:5
             7:        0x105767ccd - std::sys_common::backtrace::print::ha0747cec3f48ad89
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/sys_common/backtrace.rs:35:9
             8:        0x105767ccd - std::panicking::default_hook::{{closure}}::h0e76f92bbb367061
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:295:22
             9:        0x1057679b1 - std::panicking::default_hook::hbbbb8c05ad6cce9a
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:314:9
            10:        0x10576824e - std::panicking::rust_panic_with_hook::ha581a2c99399f83b
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:698:17
            11:        0x1057437ab - std::panicking::begin_panic::{{closure}}::hc57fe083ca1eea73
            12:        0x105743777 - std::sys_common::backtrace::__rust_end_short_backtrace::h9620d44d0f370b03
            13:        0x105785b6d - std::panicking::begin_panic::hedb03f8528414ed1
            14:        0x10573fcc3 - _LLVMInitializeBPFTarget
            15:        0x1056d9325 - bpf_linker::llvm::init::hdf4839966017a037
            16:        0x1056d358f - bpf_linker::linker::Linker::link::h662e8b3751512a65
            17:        0x1056cb566 - bpf_linker::main::h6ca1e7dc87cd9f3a
            18:        0x1056d1126 - std::sys_common::backtrace::__rust_begin_short_backtrace::h8879b42cc2650929
            19:        0x1056bf17c - std::rt::lang_start::{{closure}}::hcac71c8faace75ca
            20:        0x10575db5a - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h45b43bdd91db95dd
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:259:13
            21:        0x10575db5a - std::panicking::try::do_call::h249f439f16aa313c
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
            22:        0x10575db5a - std::panicking::try::ha8537a1873fa2ff9
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
            23:        0x10575db5a - std::panic::catch_unwind::hffa61ccaeb4f89c5
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
            24:        0x10575db5a - std::rt::lang_start_internal::{{closure}}::h32bbf4c39987b002
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:48
            25:        0x10575db5a - std::panicking::try::do_call::h558936e01b59417c
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:492:40
            26:        0x10575db5a - std::panicking::try::h12a630e8ced1b46a
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:456:19
            27:        0x10575db5a - std::panic::catch_unwind::h539ca15d1ec773ea
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panic.rs:137:14
            28:        0x10575db5a - std::rt::lang_start_internal::hdb19fe6764e59ca8
                                         at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/rt.rs:128:20
            29:        0x1056cbd39 - _main


error: could not compile `test-ebpf` due to previous error

Caused by:
  process didn't exit successfully: `rustc --crate-name test --edition=2021 src/main.rs --error-format=json --json=diagnostic-rendered-ansi,artifacts,future-incompat --crate-type bin --emit=dep-info,link -C opt-level=3 -C panic=abort -C lto -C codegen-units=1 -C metadata=2e82d0e5b2d39d7d -C extra-filename=-2e82d0e5b2d39d7d --out-dir /private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps --target bpfel-unknown-none -L dependency=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps -L dependency=/private/tmp/test/test-ebpf/../target/debug/deps --extern aya_bpf=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_bpf-8eafcb4491315b37.rlib --extern aya_log_ebpf=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libaya_log_ebpf-dab76645e270effc.rlib --extern 'noprelude:compiler_builtins=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libcompiler_builtins-fb7baa4459bc0f28.rlib' --extern 'noprelude:core=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libcore-ac93b7c2e8668cc4.rlib' --extern test_common=/private/tmp/test/test-ebpf/../target/bpfel-unknown-none/debug/deps/libtest_common-46aaf21c6fd808b3.rlib -Z unstable-options` (exit status: 1)
thread 'main' panicked at 'assertion failed: status.success()', xtask/src/build_ebpf.rs:62:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by alessandrod** [comment]
When using system-llvm, you need to have static LLVM, so you should build with `-DBUILD_SHARED_LIBS=OFF`

**Comment by alessandrod** [comment]
But have you tried  with it OFF? Because in your message above you had:

```
cmake -DLLVM_ENABLE_PROJECTS=clang -DCMAKE_BUILD_TYPE=Release -DBUILD_SHARED_LIBS=ON -G "Unix Makefiles" ../llvm
```

Which will disable static libs I think
