### ISSUE TITLE
aya-log sometimes panic

### ISSUE THREAD

**Issue by Hanaasagi** [aya-rs/aya#565]
### Describe the bug

I recently discovered that aya-log sometimes crash on my laptop. I have been using Aya to develop a simple tool that bypasses the TCP/IP stack using eBPF when certain applications are running on the same host. If suddenly there is a lot of traffic, aya-log will be crashed.

![2023-04-01_23-50](https://user-images.githubusercontent.com/9482395/229301746-ab396a51-4fef-4b16-84b6-6c0d5dad549a.png)

### Version

- aya-log 0.1.13
- ArchLinux, Kernel 6.2.8-arch1-1

### Logs/tracebacks
<details>
<summary>Full log</summary>

```
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/aya-log-0.1.13/src/lib.rs:110:45
stack backtrace:
   0: rust_begin_unwind
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/std/src/panicking.rs:579:5
   1: core::panicking::panic_fmt
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/core/src/panicking.rs:64:14
   2: core::result::unwrap_failed
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/core/src/result.rs:1750:5
   3: core::result::Result<T,E>::unwrap
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/core/src/result.rs:1090:23
   4: aya_log::BpfLogger::init_with_logger::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/aya-log-0.1.13/src/lib.rs:110:25
   5: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/core.rs:223:17
   6: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
   7: tokio::runtime::task::core::Core<T,S>::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/core.rs:212:13
   8: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/harness.rs:476:19
   9: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/core/src/panic/unwind_safe.rs:271:9
  10: std::panicking::try::do_call
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/std/src/panicking.rs:487:40
  11: __rust_try
  12: std::panicking::try
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/std/src/panicking.rs:451:19
  13: std::panic::catch_unwind
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/std/src/panic.rs:140:14
  14: tokio::runtime::task::harness::poll_future
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  15: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  16: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  17: tokio::runtime::task::raw::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/raw.rs:255:5
  18: tokio::runtime::task::raw::RawTask::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  19: tokio::runtime::task::LocalNotified<S>::run
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/mod.rs:394:9
  20: tokio::runtime::scheduler::multi_thread::worker::Context::run_task::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:464:13
  21: tokio::runtime::coop::with_budget
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/coop.rs:107:5
  22: tokio::runtime::coop::budget
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/coop.rs:73:5
  23: tokio::runtime::scheduler::multi_thread::worker::Context::run_task
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:463:9
  24: tokio::runtime::scheduler::multi_thread::worker::Context::run
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:433:24
  25: tokio::runtime::scheduler::multi_thread::worker::run::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:406:17
  26: tokio::macros::scoped_tls::ScopedKey<T>::set
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/macros/scoped_tls.rs:61:9
  27: tokio::runtime::scheduler::multi_thread::worker::run
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:403:5
  28: tokio::runtime::scheduler::multi_thread::worker::Launch::launch::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/scheduler/multi_thread/worker.rs:365:45
  29: <tokio::runtime::blocking::task::BlockingTask<T> as core::future::future::Future>::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/blocking/task.rs:42:21
  30: tokio::runtime::task::core::Core<T,S>::poll::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/core.rs:223:17
  31: tokio::loom::std::unsafe_cell::UnsafeCell<T>::with_mut
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/loom/std/unsafe_cell.rs:14:9
  32: tokio::runtime::task::core::Core<T,S>::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/core.rs:212:13
  33: tokio::runtime::task::harness::poll_future::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/harness.rs:476:19
  34: <core::panic::unwind_safe::AssertUnwindSafe<F> as core::ops::function::FnOnce<()>>::call_once
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/core/src/panic/unwind_safe.rs:271:9
  35: std::panicking::try::do_call
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/std/src/panicking.rs:487:40
  36: __rust_try
  37: std::panicking::try
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/std/src/panicking.rs:451:19
  38: std::panic::catch_unwind
             at /rustc/ff4b772f805ec1e1c1bd7e189ab8d5a4e3a6ef13/library/std/src/panic.rs:140:14
  39: tokio::runtime::task::harness::poll_future
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/harness.rs:464:18
  40: tokio::runtime::task::harness::Harness<T,S>::poll_inner
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/harness.rs:198:27
  41: tokio::runtime::task::harness::Harness<T,S>::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/harness.rs:152:15
  42: tokio::runtime::task::raw::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/raw.rs:255:5
  43: tokio::runtime::task::raw::RawTask::poll
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/raw.rs:200:18
  44: tokio::runtime::task::UnownedTask<S>::run
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/task/mod.rs:431:9
  45: tokio::runtime::blocking::pool::Task::run
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/blocking/pool.rs:159:9
  46: tokio::runtime::blocking::pool::Inner::run
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/blocking/pool.rs:513:17
  47: tokio::runtime::blocking::pool::Spawner::spawn_thread::{{closure}}
             at /home/kumiko/.cargo/registry/src/mirrors.ustc.edu.cn-61ef6e0cd06fb9b8/tokio-1.27.0/src/runtime/blocking/pool.rs:471:13
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

</details>

**Comment by Hanaasagi** [comment]
Currently I can't find which log is causing this problem, my code doesn't appear in the traceback. Maybe this problem is the same as #513

**Comment by sak96** [comment]
there is also a possibility of Buffer fill up.
https://github.com/aya-rs/aya/blob/b13070a3429033700f8d13b4f01f81d4ede07fe1/aya-log/src/lib.rs#L106

**Comment by jannes** [comment]
i'm encountering the same, but for the `aya-hello-xd` example from the book.
```
[2023-05-15T07:19:45Z INFO  aya_hello_xdp] Waiting for Ctrl-C...
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/jannes/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.13/src/lib.rs:110:45
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/jannes/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.13/src/lib.rs:110:45
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/jannes/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.13/src/lib.rs:110:45
thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/jannes/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.13/src/lib.rs:110:45
```

The following unwrap is the one that panics:
```
log_buf(buf, &*log).unwrap();
```

Same aya-log version as OP and I'm on Ubuntu 22.04:
```
Linux 1W5XKN3 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by evopen** [comment]
There's an easy solution for me. 
In the aya-template, the kernel space bpf package is not in the root workspace, hence `cargo update` will not update aya dependencies in the kernel space package. 

Incompatible dependency versions are the cause.

**Comment by jannes** [comment]
@evopen 

thanks for pointing that out. unfortunately it's not the cause of the problem for me, dependency version were in sync.

**Comment by Hanaasagi** [comment]
@jannes 
I'm not sure if you're facing the same issue as me. I did some debugging on this problem before, which might be helpful to you. In my environment, I found that `try_read` returns `Err(())` because the len value that it reads is a very large number, not the actual length.

code piece from aya-log 0.1.13:
https://github.com/aya-rs/aya/blob/832bdd280c19095d79ba2d27281c17f0b09adc15/aya-log/src/lib.rs#L501C29-L525

And I found that this piece of code has already been modified in the master branch, but I'm not sure if this issue has been fixed.

**Comment by 21kyu** [comment]
I'm experiencing the same issue.
Has anyone managed to solve it?

`Thread 'tokio-runtime-worker' panicked at 'called 'Result::unwrap()' on an 'Err' value: ()', /home/wq/.cargo/registry/src/github.com-1ecc6299db9ec823/aya-log-0.1.13/src/lib.rs:110:45`

- Asahi Linux, 6.2.0-asahi-11-1-ARCH
- LLVM 16.0.3

**Comment by Hanaasagi** [comment]
> I'm experiencing the same issue. I always get an error. Has anyone managed to solve it?

If a panic occurs every time, it's also possible that an incorrect log format is being used. See https://github.com/aya-rs/aya/issues/513

**Comment by 21kyu** [comment]
@Hanaasagi I created an XDP type project via `cargo generate` according to https://aya-rs.dev/book/start/hello-xdp/ and built and ran it without any modifications, but I will check the log formats as you mentioned.
Thanks for your response.

**Comment by 21kyu** [comment]
As you said, this was the problem.

```rust
unsafe fn try_xdp_hello(ctx: XdpContext) -> Result<u32, u32> {
    info!(&ctx, "received a packet");
    Ok(xdp_action::XDP_PASS)
}
```

I commented out the logs and ran it, and it worked fine until load and attach.
The use of `info!` seems to be the issue in my environment, I'll have to do some more checking.

**Comment by Hanaasagi** [comment]
Hi @21kyu 

I tried to reproduce your issue by creating a new `xdp-hello` project using `cargo generate`. I found that the data written in the eBPF probe cannot be correctly read in user space. The probe and user space depend on different versions of aya. You can try applying the following diff patch:

```diff
diff --git a/xdp-hello/Cargo.toml b/xdp-hello/Cargo.toml
index e690b6e..467165b 100644
--- a/xdp-hello/Cargo.toml
+++ b/xdp-hello/Cargo.toml
@@ -5,8 +5,10 @@ edition = "2021"
 publish = false
 
 [dependencies]
-aya = { version = ">=0.11", features=["async_tokio"] }
-aya-log = "0.1"
+# aya = { version = ">=0.11", features=["async_tokio"] }
+# aya-log = "0.1"
+aya = { git="https://github.com/aya-rs/aya", features=["async_tokio"] }
+aya-log = {git="https://github.com/aya-rs/aya"}
 
 clap = { version = "4.1", features = ["derive"] }
 xdp-hello-common = { path = "../xdp-hello-common", features = ["user"] }

```

**Comment by 21kyu** [comment]
@Hanaasagi Wow... it works so well.
Thank you so much!

**Comment by Hanaasagi** [comment]
After I upgrade all dependency version, it seems that the problem is no longer there :eyes:
